# Creating Numpy array

In [2]:
import numpy as np

In [3]:
np.array([2,4,56,422,32,1])  # 1D Array

array([  2,   4,  56, 422,  32,   1])

In [4]:
a =  np.array([2,4,56,422,32,1]) # Vector
print(a)

[  2   4  56 422  32   1]


In [5]:
type(a)  #type() it will give the data type

numpy.ndarray

In [6]:
new = np.array([[45,34,22,2],[24,55,3,22]])  # 2D Array (Matrix)
print(new)

[[45 34 22  2]
 [24 55  3 22]]


In [7]:
np.array([[2 ,3 ,33 ,4 ,45],[ 23 ,45 ,56 ,66 ,2],[ 357 ,523 ,32 ,24 ,2],[ 32, 32, 44, 33, 234]]  )  # 3D Array (Tensor)

array([[  2,   3,  33,   4,  45],
       [ 23,  45,  56,  66,   2],
       [357, 523,  32,  24,   2],
       [ 32,  32,  44,  33, 234]])

In [8]:
np.array([11,23,44],dtype=float) # dtype() it will convert the elements data type to mention data type

array([11., 23., 44.])

In [9]:
np.array([11,23,44],dtype=bool) # because here python treats non zero as True

array([ True,  True,  True])

In [10]:
np.array([11,23,44],dtype=complex)

array([11.+0.j, 23.+0.j, 44.+0.j])

In [11]:
np.arange(1,25) # it will print from 1 to 24

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [12]:
np.arange(1,25,2) # it will print from 1 to 24 but skip by 2

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

In [13]:
np.arange(1,11).reshape(5,2)  # converted 5 rows and 2 columns

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [14]:
np.arange(1,13).reshape(3,4)  # converted 3 rows and 4 columns

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

# Ones and zeros

In [15]:
np.ones(3) 

array([1., 1., 1.])

In [16]:
np.ones((3,4)) 

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [17]:
np.zeros(3)

array([0., 0., 0.])

In [18]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [19]:
np.random.rand(3)  # it will generate the random b/w 0 to 1 but except 1

array([0.74782424, 0.06713667, 0.00665346])

In [20]:
np.random.rand(3,3)

array([[0.92518688, 0.17946659, 0.09592674],
       [0.06495112, 0.11684367, 0.40250777],
       [0.78500738, 0.51032606, 0.61779702]])

In [21]:
np.random.randint(-10,10,10) # it will generate the random numbers b/w -10 to 10 of size 10 and start < end

array([ 7, -8, -1,  0,  4, -1, -3, -4,  6, -3], dtype=int32)

In [22]:
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [23]:
np.identity(1)

array([[1.]])

In [24]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [25]:
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

# Array Attributes

In [26]:
a1 = np.arange(10)
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
a2 = np.arange(10,dtype=float).reshape(5,2)  # reshape() it will reshape the matrix in 2D(matrix)
a2

array([[0., 1.],
       [2., 3.],
       [4., 5.],
       [6., 7.],
       [8., 9.]])

In [28]:
a3 = np.arange(12).reshape(3,2,2)   # 3D(Tensor) 
a3 

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

# ndim :It will find the number of dimensions

In [29]:
print(f"{a1.ndim}D Array")  
print(f"{a2.ndim}D Array")
print(f"{a3.ndim}D Array")

1D Array
2D Array
3D Array


# Shape: It will give the no of rows and column

In [30]:
print(a1.shape)
print(a2.shape)
print(a3.shape)

(10,)
(5, 2)
(3, 2, 2)


# Size: gives number of items

In [31]:
print(a1.size)
print(a2.size)
print(a3.size)

10
10
12


# Item size : Memory Occupied by the item

In [32]:
print(a1)
print(a1.itemsize,"bytes")
print(a2)
print(a2.itemsize,"bytes")
print(a3)
print(a3.itemsize,"bytes")

[0 1 2 3 4 5 6 7 8 9]
8 bytes
[[0. 1.]
 [2. 3.]
 [4. 5.]
 [6. 7.]
 [8. 9.]]
8 bytes
[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]
8 bytes


# dtype : gives data type of the item

In [33]:
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int64
float64
int64


# astype : Will change the data type

In [34]:
a = np.array([33,22,2.5])
a

array([33. , 22. ,  2.5])

In [35]:
a.astype(int)

array([33, 22,  2])

# Array operations

In [36]:
z1 = np.arange(12).reshape(3,4)
z2 = np.arange(12,24).reshape(3,4)

In [37]:
z1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [38]:
z2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

# scalar operations : Scalar operations on Numpy arrays include performing addition or subtraction, or multiplication on each element of a Numpy array.

In [39]:
# Addition
z1+2

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [40]:
# Subtraction
z1-2

array([[-2, -1,  0,  1],
       [ 2,  3,  4,  5],
       [ 6,  7,  8,  9]])

In [41]:
# Multiplication
z1*2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [42]:
# Power
z1**2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [43]:
# Modulus
z1%2

array([[0, 1, 0, 1],
       [0, 1, 0, 1],
       [0, 1, 0, 1]])

# relational Operators: The relational operators are also known as comparison operators, their main function is to return either a true or false based on the value of operands

In [44]:
z1 >2

array([[False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

# Vector Operation : We can apply on both array

In [45]:
print(z1)
print(" ")
print(z2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
 
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [46]:
z1 + z2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [47]:
z1 *z2

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

In [48]:
z1-z2

array([[-12, -12, -12, -12],
       [-12, -12, -12, -12],
       [-12, -12, -12, -12]])

In [49]:
z1/z2

array([[0.        , 0.07692308, 0.14285714, 0.2       ],
       [0.25      , 0.29411765, 0.33333333, 0.36842105],
       [0.4       , 0.42857143, 0.45454545, 0.47826087]])

# Array Functions

In [50]:
k1 = np.random.random((3,3))
print(k1)
print(" ")
k1 = np.round(k1*100)
print(k1)

[[0.4650753  0.73454615 0.89207798]
 [0.39336776 0.47013859 0.02314895]
 [0.03098391 0.09624416 0.97836523]]
 
[[47. 73. 89.]
 [39. 47.  2.]
 [ 3. 10. 98.]]


In [51]:
np.max(k1)

np.float64(98.0)

In [52]:
np.min(k1)

np.float64(2.0)

In [53]:
np.sum(k1)

np.float64(408.0)

In [54]:
np.prod(k1)

np.float64(3291171516360.0)

# In numpy : 0 = column and 1 = Row

In [55]:
k1

array([[47., 73., 89.],
       [39., 47.,  2.],
       [ 3., 10., 98.]])

In [56]:
np.max(k1,axis=0)  # max column wise

array([47., 73., 98.])

In [57]:
np.min(k1,axis=1)  # min row wise

array([47.,  2.,  3.])

In [58]:
np.prod(k1,axis=1)  # prod row wise

array([305359.,   3666.,   2940.])

# Statistics related fuctions

In [59]:
k1

array([[47., 73., 89.],
       [39., 47.,  2.],
       [ 3., 10., 98.]])

In [60]:
np.mean(k1)

np.float64(45.333333333333336)

In [61]:
k1.mean(axis=0) # mean column wise

array([29.66666667, 43.33333333, 63.        ])

In [62]:
np.median(k1)

np.float64(47.0)

In [63]:
np.median(k1,axis =1) # median row wise

array([73., 39., 10.])

In [64]:
np.std(k1)

np.float64(34.009802508492555)

In [65]:
np.std(k1,axis= 0) # standard deviation column wise

array([19.13693346, 25.84999463, 43.28972164])

In [66]:
np.var(k1)

np.float64(1156.6666666666667)

# Trignometry Functions

In [67]:
np.sin(k1)

array([[ 0.12357312, -0.67677196,  0.86006941],
       [ 0.96379539,  0.12357312,  0.90929743],
       [ 0.14112001, -0.54402111, -0.57338187]])

In [68]:
np.cos(k1)

array([[-0.99233547, -0.73619272,  0.51017704],
       [ 0.26664293, -0.99233547, -0.41614684],
       [-0.9899925 , -0.83907153, -0.81928825]])

In [69]:
np.tan(k1)

array([[-0.12452757,  0.9192864 ,  1.68582537],
       [ 3.61455441, -0.12452757, -2.18503986],
       [-0.14254654,  0.64836083,  0.69985365]])

# Dot product : The numpy module of Python provides a function to perform the dot product of two arrays.

In [70]:
s1 = np.arange(9).reshape(3,3)
s2 = np.arange(9,18).reshape(3,3)


In [71]:
print(s1)
print(" ")
print(s2)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
 
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]


In [72]:
np.dot(s1,s2)

array([[ 42,  45,  48],
       [150, 162, 174],
       [258, 279, 300]])

# Log and Exponents

In [73]:
np.exp(s2)

array([[8.10308393e+03, 2.20264658e+04, 5.98741417e+04],
       [1.62754791e+05, 4.42413392e+05, 1.20260428e+06],
       [3.26901737e+06, 8.88611052e+06, 2.41549528e+07]])

# round / floor /ceil

In [74]:
arr= np.array([ 1.234 , 2.567 , 3.891 ])
print(np.round(arr))                      # Round to the nearest integer
print(np.round(arr,decimals=2))          # Round to two decimals

[1. 3. 4.]
[1.23 2.57 3.89]


In [75]:
arr= np.array([ 1.234 , 2.567 , 3.891 ])
print(np.floor(arr))          
print(np.ceil(arr))

[1. 2. 3.]
[2. 3. 4.]


# Indexing and slicing

In [76]:
p1 = np.arange(10)
p2 = np.arange(12).reshape(3,4)
p3 = np.arange(8).reshape(2,2,2)

In [77]:
p1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [78]:
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [79]:
p3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

# Indexing on 1D array

In [80]:
p1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [81]:
p1[-1]

np.int64(9)

In [82]:
p1[0]

np.int64(0)

# indexing on 2D array

In [83]:
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [84]:
p2[1,2] # 1st row and 2nd column

np.int64(6)

In [85]:
p2[2,3]

np.int64(11)

# indexing on 3D ( Tensors)

In [86]:
p3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [87]:
p3[1,0,1]

np.int64(5)

In [88]:
p3[0,0,1]

np.int64(1)

# Slicing on 1D

In [89]:
p1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [90]:
p1[2:5]

array([2, 3, 4])

In [91]:
p1[2:5:2]

array([2, 4])

# Slicing on 2D

In [92]:
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [93]:
p2[1:2]

array([[4, 5, 6, 7]])

In [94]:
p2[:,1]

array([1, 5, 9])

In [95]:
p2[1:3,0:4]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [96]:
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [97]:
p2[::2]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11]])

In [98]:
p2[:,::2]

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

In [99]:
p2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

# Slicing in 3D

In [100]:
p3 = np.arange(8).reshape(2,2,2)
p3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [101]:
p3[0]

array([[0, 1],
       [2, 3]])

In [102]:
p3[1,0,1]

np.int64(5)

In [103]:
p3[1:2,0:1,1:2]

array([[[5]]])

# Iterating

In [104]:
p1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Looping on 1D

In [105]:

for i in p1:
    print(i)

0
1
2
3
4
5
6
7
8
9


## Looping on 2D


In [106]:
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [107]:
for i in p2:  # print the rows
    print(i)
    

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [108]:
p2.shape

(3, 4)

In [109]:
p2.shape[1]

4

In [110]:
for i in range(p2.shape[1]):
    print(p2[:,i])

[0 4 8]
[1 5 9]
[ 2  6 10]
[ 3  7 11]


## Looping on 3D array

In [111]:
p3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [112]:
for i in p3:
    print(i)

[[0 1]
 [2 3]]
[[4 5]
 [6 7]]


# nditer : print all items in 3D using nditer ---- > first convert in to 1D and applying Loop

In [113]:
for i in np.nditer(p3):
    print(i)

0
1
2
3
4
5
6
7


Transpose ---> Converts rows in to clumns ad columns into rows

In [114]:
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [115]:
np.transpose(p2)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [116]:
p2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

# Ravel : Converting any dimensions to 1D

In [117]:
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [118]:
np.ravel(p2)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

# Stacking

In [119]:
w1 = np.arange(12).reshape(3,4)
w2 = np.arange(12,24).reshape(3,4)

In [120]:
w1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [121]:
w2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [122]:
# Horizontal stacking
hs=np.hstack((w1,w2))
hs

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [123]:
# Vertical stacking
vs=np.vstack((w1,w2))
vs

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

# Splitting: its opposite of Stacking

In [124]:
# Horizontal splitting
w1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [125]:
np.hsplit(w1,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [126]:
#  Vertical splitting
np.vsplit(w1,3)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]

# Speed of List Vs Numpy

In [127]:
# List
a= [i for i in range(10000000)]
b= [i for i in range(10000000,20000000)]
c= []
import time
start = time.time()
for i in range(len(a)):
    c.append(a[i] + b[i])
print(time.time()-start)

1.8022584915161133


In [128]:
# Numpy
import numpy as np
a= np.arange(10000000)
b= np.arange(10000000,20000000)
start = time.time()
c= a+b
print(time.time()-start)

0.10973906517028809


In [129]:
p = [i for i in range(10000000)]
import sys # it give direct access to the python interpreter and environment it runs in 
sys.getsizeof(p)

89095160

In [130]:
r = np.arange(10000000)
sys.getsizeof(r)

80000112

In [131]:
r = np.arange(10000000,dtype=np.int16)
sys.getsizeof(r)

20000112

# Advance Indexing and Slicing

In [132]:
w = np.arange(12).reshape(4,3)
w

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [133]:
w[1,2]

np.int64(5)

In [134]:
w[1:3,1:3]

array([[4, 5],
       [7, 8]])

# Fancy Indexing 
- Simple indexing: arr[3] → gets one element.
- Fancy indexing: arr[[1, 2, 5, 7]] → gets multiple elements at once.
- It returns a new array, independent of the original.


In [135]:
arr = np.array([10,20,30,40,50,60,70,80])
selected = arr[[1,3,5]]
print(selected)

[20 40 60]


In [136]:
w

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [137]:
w[[0,2,3]] # fetch rows

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [138]:
w[:,[0,2]] # fetch columns

array([[ 0,  2],
       [ 3,  5],
       [ 6,  8],
       [ 9, 11]])

In [139]:
w[[0,2],[1,2]]

array([1, 8])

# Boolean indexing

In [140]:
G = np.random.randint(1,100,24).reshape(6,4)
G

array([[ 6, 18, 70, 10],
       [47, 46, 76, 87],
       [12, 84, 32, 75],
       [31, 26,  7, 97],
       [ 2, 21, 31, 41],
       [ 8, 17, 18, 55]], dtype=int32)

In [141]:
G>50

array([[False, False,  True, False],
       [False, False,  True,  True],
       [False,  True, False,  True],
       [False, False, False,  True],
       [False, False, False, False],
       [False, False, False,  True]])

In [142]:
G[G>50]

array([70, 76, 87, 84, 75, 97, 55], dtype=int32)

In [143]:
G%2==0

array([[ True,  True,  True,  True],
       [False,  True,  True, False],
       [ True,  True,  True, False],
       [False,  True, False, False],
       [ True, False, False, False],
       [ True, False,  True, False]])

In [144]:
G[G%2==0]   # find the even numbers

array([ 6, 18, 70, 10, 46, 76, 12, 84, 32, 26,  2,  8, 18], dtype=int32)

In [145]:
# find the numbers greater than 50 and even
(G>50) & (G%2==0)

array([[False, False,  True, False],
       [False, False,  True, False],
       [False,  True, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [146]:
G[(G>50)&(G%2==0)]

array([70, 76, 84], dtype=int32)

In [147]:
# find all numbers not divisible by 7
G%7== 0

array([[False, False,  True, False],
       [False, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False,  True, False, False],
       [False, False, False, False]])

In [148]:
G[G%7==0]

array([70, 84,  7, 21], dtype=int32)

In [149]:
G[~(G%7==0)] # ~ (not)

array([ 6, 18, 10, 47, 46, 76, 87, 12, 32, 75, 31, 26, 97,  2, 31, 41,  8,
       17, 18, 55], dtype=int32)

# Broadcasting: Used in Vectorization
The term broadcasting describes how NumPy treats arrays with different shapes during arithmetic operations.

# Broadcasting Rules
1. Make the two arrays have the same number of dimensions.
2. Make each dimension of the two arrays the same size.

(3,1) + (1,4) = (3,4)  in first column i.e, (1) = in second row i.e, (1) braodcasting possible

# Broadcasting Rules
NumPy compares array shapes from right to left:
- If dimensions are equal → ✅ compatible.
- If one dimension is 1 → ✅ it can be stretched.
- If neither matches → ❌ error.
- The result shape is the maximum size in each dimension.


# Working with Missing Values


In [150]:
# Working with missing values -> np.nan
S = np.array([1,2,3,4,np.nan,6])
S

array([ 1.,  2.,  3.,  4., nan,  6.])

In [151]:
np.isnan(S)

array([False, False, False, False,  True, False])

In [ ]:
S[np.isnan(S)]  # null values

array([nan])

In [153]:
S[~np.isnan(S)] # Not NullValues

array([1., 2., 3., 4., 6.])

# docstring
A docstring is a special string in Python that documents a module, class, function, or method. It explains what the code does, how to use it, and sometimes gives examples.


In [154]:
def add(a, b):
    """
    Add two numbers and return the result.

    Parameters:
        a (int or float): First number
        b (int or float): Second number

    Returns:
        int or float: Sum of a and b
    """
    return a + b

In [157]:
a=add(3,4)
print(a)

7


In [ ]:
print(add.__doc__) # to access the text written by us


Add two numbers and return the result.

Parameters:
    a (int or float): First number
    b (int or float): Second number

Returns:
    int or float: Sum of a and b



In [161]:
# Function Docstring
def greet(name):
    """Return a friendly greeting."""
    return f"Hello, {name}!"

print(greet.__doc__)
# Output: Return a friendly greeting.

Return a friendly greeting.


In [162]:
# class Docstring
class Dog:
    """A simple Dog class."""
    pass

print(Dog.__doc__)
# Output: A simple Dog class.

A simple Dog class.
